ls:
  .dir: regex:[a-z0-9]+(?:-[a-z0-9]+)*
  .ts: regex:.*          # start permissive
  .tsx: regex:.*         # start permissive
  .js: regex:.*
  .jsx: regex:.*
  .json: regex:.*

ignore:
  - .git
  - .github
  - node_modules
  - dist
  - build
  - coverage
  - .turbo
  - .next
  - .vercel
  - .output
  - .cache
  - services/api/migrations/_archive
